### ISSUE TITLE
`HSV.initFromRgb()` doesn't handle grayscale colors

### ISSUE THREAD

**Issue by MadLittleMods** [nitrogenez/prism#1]
As far as I can tell, when you provide a grayscale RGB color like `(1, 1, 1)`, `HSV.initFromRgb()` will just return HSV `(0, 0, 0)` when it should at least have  a `V` value.

To fix the problem, I think we just need to move the `hsv[2] = max;` line after we find the max/min and create the initial `hsv` value.

https://github.com/nitrogenez/prism/blob/9152942425546f6110bd0202d7671d6ff5b25de5/src/spaces/HSV.zig#L9-L40

**Comment by nitrogenez** [comment]
fixed in 659a97b
